project_name: tagbot
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
    - '-s -w -X github.com/nicjohnson145/tagbot/cmd.version={{.Version}} -X github.com/nicjohnson145/tagbot/cmd.date={{.Date}}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    # Per https://goreleaser.com/customization/archive/#packaging-only-the-binaries
    files:
      - none*
changelog:
  filters:
    exclude:
      - '^Merge pull request #'
      - '^Merge branch .* into main$'