// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package config

import (
	"fmt"
	"strings"
)

const (
	// AuthKindPublicKey is a AuthKind of type public-key.
	AuthKindPublicKey AuthKind = "public-key"
	// AuthKindToken is a AuthKind of type token.
	AuthKindToken AuthKind = "token"
)

var ErrInvalidAuthKind = fmt.Errorf("not a valid AuthKind, try [%s]", strings.Join(_AuthKindNames, ", "))

var _AuthKindNames = []string{
	string(AuthKindPublicKey),
	string(AuthKindToken),
}

// AuthKindNames returns a list of possible string values of AuthKind.
func AuthKindNames() []string {
	tmp := make([]string, len(_AuthKindNames))
	copy(tmp, _AuthKindNames)
	return tmp
}

// String implements the Stringer interface.
func (x AuthKind) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuthKind) IsValid() bool {
	_, err := ParseAuthKind(string(x))
	return err == nil
}

var _AuthKindValue = map[string]AuthKind{
	"public-key": AuthKindPublicKey,
	"token":      AuthKindToken,
}

// ParseAuthKind attempts to convert a string to a AuthKind.
func ParseAuthKind(name string) (AuthKind, error) {
	if x, ok := _AuthKindValue[name]; ok {
		return x, nil
	}
	return AuthKind(""), fmt.Errorf("%s is %w", name, ErrInvalidAuthKind)
}

// MarshalText implements the text marshaller method.
func (x AuthKind) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *AuthKind) UnmarshalText(text []byte) error {
	tmp, err := ParseAuthKind(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *AuthKind) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// LoggingLevelTrace is a LoggingLevel of type trace.
	LoggingLevelTrace LoggingLevel = "trace"
	// LoggingLevelDebug is a LoggingLevel of type debug.
	LoggingLevelDebug LoggingLevel = "debug"
	// LoggingLevelInfo is a LoggingLevel of type info.
	LoggingLevelInfo LoggingLevel = "info"
	// LoggingLevelWarning is a LoggingLevel of type warning.
	LoggingLevelWarning LoggingLevel = "warning"
	// LoggingLevelError is a LoggingLevel of type error.
	LoggingLevelError LoggingLevel = "error"
)

var ErrInvalidLoggingLevel = fmt.Errorf("not a valid LoggingLevel, try [%s]", strings.Join(_LoggingLevelNames, ", "))

var _LoggingLevelNames = []string{
	string(LoggingLevelTrace),
	string(LoggingLevelDebug),
	string(LoggingLevelInfo),
	string(LoggingLevelWarning),
	string(LoggingLevelError),
}

// LoggingLevelNames returns a list of possible string values of LoggingLevel.
func LoggingLevelNames() []string {
	tmp := make([]string, len(_LoggingLevelNames))
	copy(tmp, _LoggingLevelNames)
	return tmp
}

// String implements the Stringer interface.
func (x LoggingLevel) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x LoggingLevel) IsValid() bool {
	_, err := ParseLoggingLevel(string(x))
	return err == nil
}

var _LoggingLevelValue = map[string]LoggingLevel{
	"trace":   LoggingLevelTrace,
	"debug":   LoggingLevelDebug,
	"info":    LoggingLevelInfo,
	"warning": LoggingLevelWarning,
	"error":   LoggingLevelError,
}

// ParseLoggingLevel attempts to convert a string to a LoggingLevel.
func ParseLoggingLevel(name string) (LoggingLevel, error) {
	if x, ok := _LoggingLevelValue[name]; ok {
		return x, nil
	}
	return LoggingLevel(""), fmt.Errorf("%s is %w", name, ErrInvalidLoggingLevel)
}

// MarshalText implements the text marshaller method.
func (x LoggingLevel) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *LoggingLevel) UnmarshalText(text []byte) error {
	tmp, err := ParseLoggingLevel(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *LoggingLevel) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// RemoteTypeSsh is a RemoteType of type ssh.
	RemoteTypeSsh RemoteType = "ssh"
	// RemoteTypeHttps is a RemoteType of type https.
	RemoteTypeHttps RemoteType = "https"
)

var ErrInvalidRemoteType = fmt.Errorf("not a valid RemoteType, try [%s]", strings.Join(_RemoteTypeNames, ", "))

var _RemoteTypeNames = []string{
	string(RemoteTypeSsh),
	string(RemoteTypeHttps),
}

// RemoteTypeNames returns a list of possible string values of RemoteType.
func RemoteTypeNames() []string {
	tmp := make([]string, len(_RemoteTypeNames))
	copy(tmp, _RemoteTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x RemoteType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RemoteType) IsValid() bool {
	_, err := ParseRemoteType(string(x))
	return err == nil
}

var _RemoteTypeValue = map[string]RemoteType{
	"ssh":   RemoteTypeSsh,
	"https": RemoteTypeHttps,
}

// ParseRemoteType attempts to convert a string to a RemoteType.
func ParseRemoteType(name string) (RemoteType, error) {
	if x, ok := _RemoteTypeValue[name]; ok {
		return x, nil
	}
	return RemoteType(""), fmt.Errorf("%s is %w", name, ErrInvalidRemoteType)
}

// MarshalText implements the text marshaller method.
func (x RemoteType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *RemoteType) UnmarshalText(text []byte) error {
	tmp, err := ParseRemoteType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *RemoteType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
