// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package bot

import (
	"fmt"
	"strings"
)

const (
	// VersionBumpNone is a VersionBump of type None.
	VersionBumpNone VersionBump = iota
	// VersionBumpPatch is a VersionBump of type Patch.
	VersionBumpPatch
	// VersionBumpMinor is a VersionBump of type Minor.
	VersionBumpMinor
	// VersionBumpMajor is a VersionBump of type Major.
	VersionBumpMajor
)

var ErrInvalidVersionBump = fmt.Errorf("not a valid VersionBump, try [%s]", strings.Join(_VersionBumpNames, ", "))

const _VersionBumpName = "nonepatchminormajor"

var _VersionBumpNames = []string{
	_VersionBumpName[0:4],
	_VersionBumpName[4:9],
	_VersionBumpName[9:14],
	_VersionBumpName[14:19],
}

// VersionBumpNames returns a list of possible string values of VersionBump.
func VersionBumpNames() []string {
	tmp := make([]string, len(_VersionBumpNames))
	copy(tmp, _VersionBumpNames)
	return tmp
}

var _VersionBumpMap = map[VersionBump]string{
	VersionBumpNone:  _VersionBumpName[0:4],
	VersionBumpPatch: _VersionBumpName[4:9],
	VersionBumpMinor: _VersionBumpName[9:14],
	VersionBumpMajor: _VersionBumpName[14:19],
}

// String implements the Stringer interface.
func (x VersionBump) String() string {
	if str, ok := _VersionBumpMap[x]; ok {
		return str
	}
	return fmt.Sprintf("VersionBump(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VersionBump) IsValid() bool {
	_, ok := _VersionBumpMap[x]
	return ok
}

var _VersionBumpValue = map[string]VersionBump{
	_VersionBumpName[0:4]:   VersionBumpNone,
	_VersionBumpName[4:9]:   VersionBumpPatch,
	_VersionBumpName[9:14]:  VersionBumpMinor,
	_VersionBumpName[14:19]: VersionBumpMajor,
}

// ParseVersionBump attempts to convert a string to a VersionBump.
func ParseVersionBump(name string) (VersionBump, error) {
	if x, ok := _VersionBumpValue[name]; ok {
		return x, nil
	}
	return VersionBump(0), fmt.Errorf("%s is %w", name, ErrInvalidVersionBump)
}

// MarshalText implements the text marshaller method.
func (x VersionBump) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VersionBump) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseVersionBump(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *VersionBump) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
